---
- name: install nginx and start nginx
  hosts: all
  become: yes
  tasks:
  - name: i want to install nginx on ubuntu16
    apt:
      name: nginx
      state: present
  - name: i want to start nginx services
    service:
      name: nginx
      state: started   